# Generated by Django 3.0.2 on 2022-06-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardContato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_index=True, max_length=100, unique=True)),
                ('imagem', models.CharField(blank=True, max_length=50)),
                ('texto1', models.CharField(blank=True, max_length=255)),
                ('texto2', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'card_contato',
            },
        ),
        migrations.CreateModel(
            name='CardServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_index=True, max_length=100, unique=True)),
                ('imagem', models.CharField(blank=True, max_length=50)),
                ('miniatura', models.CharField(blank=True, max_length=50)),
                ('ehNovo', models.BooleanField(default=False)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('texto', models.TextField(blank=True, max_length=1000)),
                ('slug', models.SlugField(max_length=70)),
            ],
            options={
                'db_table': 'card_servico',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=100, unique=True)),
                ('imagem', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=100, unique=True)),
                ('texto', models.TextField(blank=True, max_length=1000)),
            ],
            options={
                'db_table': 'objetivo',
            },
        ),
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(db_index=True, max_length=14, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=300)),
                ('telefone', models.CharField(max_length=11)),
                ('data_cadastro', models.DateField()),
            ],
            options={
                'db_table': 'parceiros',
            },
        ),
    ]
