# Generated by Django 3.0.2 on 2022-06-18 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_parceiro_data_atualizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('qtd_estoque', models.IntegerField()),
                ('preco', models.IntegerField(default=0)),
                ('data_cadastro', models.DateField()),
                ('disponivel', models.BooleanField(default=False)),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='produtos', to='domain.Parceiro')),
            ],
            options={
                'db_table': 'produto',
            },
        ),
    ]
